# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /src

# Add the current directory contents into the container at /app
ADD . /src

# Install dos2unix and convert the line endings in start.sh
RUN apt-get update && apt-get install -y dos2unix
RUN dos2unix ./bin/sh/start.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x ./bin/sh/start.sh
CMD ["./bin/sh/start.sh"]